apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p6r3l78r2-java-springboot
  janus-idp.io/tekton: p6r3l78r2-java-springboot
  backstage.io/kubernetes-id: p6r3l78r2-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p6r3l78r2-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
